version: '3.5'

services:

  mysql:
    image: mysql:5.6
    ports:
      - 13306:3306
    env_file:
      - ./.env.mysql${ENV:-}
    environment:
      - TZ=GMT
    networks:
      - traefik

networks:
  traefik:
    driver: bridge
    name: traefik
