version: '3.5'

services:

  mysql:
    image: mysql:5.6
    ports:
      - 13306:3306
    env_file:
      - ./.env.mysql${ENV:-}
    environment:
      - TZ=GMT
    networks:
      - traefik

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/nodemon dist/server.js
    expose:
      - 4000
    volumes:
      - .:/app
      - /app/node_modules
      - ./bucket:/data
    environment:
      - NODE_ENV=${NODE_ENV:-stage}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.backend.loadbalancer.server.port=4000"
      - "traefik.http.routers.backend.rule=PathPrefix(`/v1`)"
      - "traefik.http.routers.backend.entrypoints=https"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.service=backend"
    depends_on:
      - mysql
      - reverse-proxy
    networks:
      - traefik

networks:
  traefik:
    driver: bridge
    name: traefik
