version: '3.5'

services:
  reverse-proxy:
    image: traefik:v2.2
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${PWD}/config/certs:/opt/certs
    labels:
      - "traefik.enable=true"
    restart: unless-stopped
    networks:
      - traefik

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/nodemon dist/server.js
    expose:
      - 4000
    volumes:
      - .:/app
      - /app/node_modules
      - ./bucket:/data
    environment:
      - NODE_ENV=${NODE_ENV:-stage}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.backend.loadbalancer.server.port=4000"
      - "traefik.http.routers.backend.rule=PathPrefix(`/v1`)"
      - "traefik.http.routers.backend.entrypoints=https"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.service=backend"
    depends_on:
      - mysql
    networks:
      - traefik

networks:
  traefik:
    driver: bridge
    name: traefik
